# Generated by Django 5.2.6 on 2025-09-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "date_of_birth",
                    models.DateField(help_text="Date of birth of patient."),
                ),
                ("phone_number", models.CharField(max_length=10)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("address", models.TextField()),
                ("medical_record", models.TextField(blank=True)),
                (
                    "assigned_doctors",
                    models.ManyToManyField(blank=True, to="doctors.doctor"),
                ),
            ],
        ),
    ]
