# Generated by Django 5.2.6 on 2025-09-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(blank=True, help_text="Date of birth of patient."),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
