# Generated by Django 5.2.6 on 2025-09-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_alter_patient_address_alter_patient_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(
                blank=True, help_text="Date of birth of patient.", null=True
            ),
        ),
    ]
