# Generated by Django 5.2.6 on 2025-09-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("joined_at", models.DateField(auto_now_add=True)),
                ("specialization", models.CharField(max_length=200)),
                ("license_number", models.CharField(max_length=50, unique=True)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
