# Generated by Django 5.2.6 on 2025-09-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="salary",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
